

language: R
sudo: required
warnings_are_errors: false

before_script:
- sudo apt-get update -qq
- sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libgdal1h geos geos-devel

r_packages:
  - rgeos
  - maptools
  - rgdal

after_success:
  - Rscript -e 'covr::codecov()'