

language: R
sudo: required
warnings_are_errors: true

before_install:
  - sudo apt-get install -y libproj-dev libgeos-dev gdal-bin libgdal-dev
  

r_packages:
 - covr
 - testthat
 - RSQLite
 - rgdal
 - rgeos
 - data.table
 - magrittr
 - foreach
 - RSQLite
 - sp
 - rgdal
 - rgeos
 - raster
 - maptools
 - lattice
 - ggplot2
 - RColorBrewer
 - classInt
 - snow

after_success:
  - Rscript -e 'covr::codecov()'


