# https://github.com/craigcitro/r-travis

language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh

install:
- ./travis-tool.sh install_deps
- ./travis-tool.sh bootstrap
- ./travis-tool.sh install_r_binary sp raster rgeos rgdal RSQLite maptools RSQLite.extfuns RColorBrewer classInt
- ./travis-tool.sh install_r_binary rgeos shiny

script: ./travis-tool.sh run_tests

notifications:
email:
on_success: change
on_failure: change